### ISSUE TITLE
Can't find Player "0"

### ISSUE THREAD

**Issue by digitalkiller** [alemart/opensurge#1]
Greetings. I just built Open Surge and wanted to launch the game. The game started, but I can't play it.

This is what brings up a new dialog box:

`[surgescript-error] Script Error: Can't find Player "0": no such player in the scene.`

Also, the menu does not work properly, I can only choose between "Play" and "Quit".

OS: Arch Linux

**Comment by alemart** [comment]
Hello,

Please send your logfile.txt, located in ~/.cache/opensurge2d/opensurge. Are you using the latest build of SurgeScript? Does the dialog box show up after you choose "Play"? What happens if you choose other options?

**Comment by digitalkiller** [comment]
Logfile: https://gist.github.com/digitalkiller/a8a6434b098dcae50d78cef4cb53035d
Yes, I use the latest SurgeScript build. Of course, the dialog box appears not only when I select "Play", but also when I select other options.

**Comment by alemart** [comment]
Make the program crash and then send your logfile. I can see that the menu is loading properly. What happens if you choose "Options"? And "share"? Same dialog box?

**Comment by digitalkiller** [comment]
Logfile: https://gist.github.com/digitalkiller/0ba3d36aea11524f92cd898809305397
_I can't_ choose any other options. Here's the video, if you don't understand: https://www.youtube.com/watch?v=zYDboBQQ15Q

(P.S.: There's sound in the game, but there's no sound in the video for some reason.)

**Comment by alemart** [comment]
Thanks for recording the video. In order to reproduce the error, I need you to send me your build. I also need data on how you built this:
- OS version
- Compiler name & version
- Full version of Allegro (did you compile it from the source?)

Additionally, open the debug mode by pressing RIGHT 3 times when you see "powered by Open Surge Engine". Load the different levels there (including surgescript.lev). What happens?

**Comment by digitalkiller** [comment]
My build: https://send.firefox.com/download/1ed52f02f58b170a/#AN2BG0eiTiVPteGo_Whm_w (temporary link)

Here's the info:

- Arch Linux uses the rolling release model (I update packages every day)
- GCC 8.3.0
- 5.2.5-1 (No, I used the precompiled version)

All levels work except waterworks-1.lev. scenes/create.lev has the same problem as the main menu.

**Comment by digitalkiller** [comment]
Oh, by the way, I just tried to use the level editor, some things from the entity palette can not be added, the same dialog box appears.

**Comment by alemart** [comment]
I have submitted new code to both Open Surge and SurgeScript repositories. You'll need to compile SurgeScript again, and then the game. Let me know how it goes.

**Comment by digitalkiller** [comment]
Yay, it's working now! Thanks!
