### ISSUE TITLE
Zone number is concatenated to CLEARED_LINE2

### ISSUE THREAD

**Issue by Wuzzy2** [alemart/opensurge#10]
The translation strings `CLEARED_LINE1` and `CLEARED_LINE2` are annoying to translate. It doesn't include the zone number as parameter. Apparently Open Surge just appends the number always at the end.

That's a problem for translating because not in all languages you can put the number at the end.

**Comment by alemart** [comment]
Thank you for pointing it out. In the latest build, you can translate using `$LEVEL_ACT`. This will be replaced by the zone number. Example:

`CLEARED_LINE2               "CLEARED ZONE $LEVEL_ACT"`

Let me know if you find any problems.

**Comment by Wuzzy2** [comment]
This is fixed now.
