### ISSUE TITLE
[Android F-Droid] Controls are weird

### ISSUE THREAD

**Issue by Dv5n** [alemart/opensurge#104]
(This is the android fdroid version)
(I know that is a prerelease and could change in the future)

The controls are a bit **hard** to control.
You could change them to look like this:

![wat](https://github.com/alemart/opensurge/assets/118058649/cc1d5ac1-ed96-46a1-aa63-f2a7ddc1c0ab)
(Arrows)
(I know, it looks so bad)

**Comment by alemart** [comment]
Hi @Dv5n ,

Thank you for your feedback.

So far I found that most players find the controls to be smooth and easy to use. I will continue to listen to their feedback to better understand their preferences before I decide on this matter.
