### ISSUE TITLE
[minor] linux menu name "Surge Engine"

### ISSUE THREAD

**Issue by pirate486743186** [alemart/opensurge#105]
The desktop file in linux (self compiled, never used the snap/flatpack package)
`/usr/share/applications/opensurge.desktop`

uses` "Surge Engine"/"Game engine"` as the name.
```
Name=Surge Engine
GenericName=Game Engine
GenericName[de]=Spiel-Engine
Comment=Open source 2D retro game engine
```

The menu entry points to the whole open surge game, not just the game engine without the assets.

It should have been something like `Open Surge` for the name
something like `Fast 2D platformer game` for the generic name
something like `A game featuring a fast rabbit rolling into a ball in a 2D platformer` for the comment

**Comment by alemart** [comment]
This is intended. You can play Surge the Rabbit and also load MODs via options screen.
