### ISSUE TITLE
Add option to disable sound

### ISSUE THREAD

**Issue by Wuzzy2** [alemart/opensurge#11]
I suggest to add a setting to disable sound.

Version 0.5.0

**Comment by alemart** [comment]
Any rationale for this? It doesn't seem to be requested too often, nor particularly appealing for most users.

**Comment by Wuzzy2** [comment]
You can disable sound in like every other game. Isn't this reason enough. Maybe I want to listen to other things (webradio, podcast, etc.). Force-enabling sound is not nice in this situation.

**Comment by alemart** [comment]
Maybe, but this feature is not in very high demand at this moment. You can use a solution such as `pavucontrol` to disable the sound in your OS.
