### ISSUE TITLE
Easy level

### ISSUE THREAD

**Issue by stokito** [alemart/opensurge#110]
The game is great but too complicated for kids. Could you make an Easy level?

**Comment by alemart** [comment]
Hi @stokito,

Thanks for the feedback!

Yes, we have easy levels that have been played by kids. We call them the classic levels.

When starting to play, pause and exit the game. When asked if you want to play on the classic levels, answer yes.

(also: the kids can [make their own levels](https://wiki.opensurge2d.org/How_to_make_a_level) - this is a fun experience for them! :grinning:)

![s104](https://github.com/alemart/opensurge/assets/221477/2757792d-7697-453e-bd72-f7fa4fc480c2)
![s105](https://github.com/alemart/opensurge/assets/221477/c048820e-e529-4f37-97b5-e75277b24019)
![s106](https://github.com/alemart/opensurge/assets/221477/c1aa2450-b748-493d-a218-cb3fe8bee701)
