### ISSUE TITLE
Unable to run on Linux Mint 21.3 (flatpak)

### ISSUE THREAD

**Issue by connorjclark** [alemart/opensurge#116]
nvidia RTX 3080 card, in case that matters.

This is fixed using the workaround suggested [here](https://github.com/alemart/opensurge/issues/109#issuecomment-2185506311) - `LIBGL_ALWAYS_SOFTWARE=1 flatpak run org.opensurge2d.OpenSurge`

My issue specifically is I get this error:

> Gtk-Message: 23:28:39.856: Failed to load module "xapp-gtk3-module"

And no window opens.

[This thread](https://forums.linuxmint.com/viewtopic.php?t=401477) may be related to the root cause, I guess it's 100% Mint / Ubuntu's fault - and according to the thread it may possibly be resolved in the next LTS Mint 22.

Figured I'd share for other Mint users to find a resolution. Feel free to close.

**Comment by alemart** [comment]
Thanks!
