### ISSUE TITLE
Add game manual

### ISSUE THREAD

**Issue by Wuzzy2** [alemart/opensurge#12]
Currently, the game is lacking even the most basic help. I suggest to create a gameplay manual.

Suggested contents:

* Introduction (about Open Surge)
* Controls
* Possible moves
* Enemies and how they affect you
* Common/important elements in levels (trampolines, checkpoint, finish sign, etc.)
* Collectibles
* Meaning of all those weird “computer screens”
* Meaning of power
* Other non-obvious mechanics

**Comment by alemart** [comment]
Currently, we have this information (and more) in our website and in the project wiki (see the website). If you would like to help the project with a game manual that condenses this information in a pdf (for example), your contribution would be welcome. Would you be interested?

I'll leave this issue open for now, in case anybody would like to join.

**Comment by alemart** [comment]
Closed due to inactivity. We may rediscuss it in the future.
