### ISSUE TITLE
[crash on startup] missing ";" in scripts/ui/title_card.ss

### ISSUE THREAD

**Issue by pirate486743186** [alemart/opensurge#121]
i suspect you simply forgot to make a release of opensurge

it worked fine with surgescript 0.6.0, it complains with surgescript 0.6.1
the error:
`[surgescript-error] Parse Error: expected ";" on scripts/ui/title_card.ss:201. `

at line 199 (201 is actually the next instruction)
there's `assert(actor !== null)` that works fine if you add the ";"

**Comment by alemart** [comment]
Already fixed in 6f44cf891e68b03d2b4d603d323016e7316e48db

> i suspect you simply forgot to make a release of opensurge

I haven't. It's coming shortly.


Em sáb, 24 de ago de 2024 06:00, pirate486743186 ***@***.***>
escreveu:
