### ISSUE TITLE
[Termux] Surgexception on shader

### ISSUE THREAD

**Issue by IntinteDAO** [alemart/opensurge#123]
Termux in a nutshell is a Linux environment running on Android. Why would anyone want to use OpenSurge using Termux? I don't know, but such a request appeared :D

I managed to recompile the code, however, I get such an error
The problem may be that I had to write a couple of patches to get the code to compile correctly on Termux (mostly because the code thinks it's supposed to compile code on Android, and we don't want that)

[log.txt](https://github.com/user-attachments/files/16936775/log.txt)

**Comment by IntinteDAO** [comment]
I enabled defined __ANDROID__ and window is now drawed, but crashed.

I have a question, is it possible to force somehow build a games as Linux on Android environment? Termux is Linux Environment on Android (Mesa, X11, Pulseaudio etc), but the code by default is builded for Android instead as in Linux. I set CMAKE_SYSTEM_NAME=Linux, but it's not respected

**Comment by alemart** [comment]
> I enabled defined ANDROID and window is now drawed, but crashed.

`#if defined(__ANDROID__)` is defined in several parts of the code and is related to the native Android builds.

> I have a question, is it possible to force somehow build a games as Linux on Android environment? Termux is Linux Environment on Android (Mesa, X11, Pulseaudio etc), but the code by default is builded for Android instead as in Linux. I set CMAKE_SYSTEM_NAME=Linux, but it's not respected

`__ANDROID__` shouldn't be defined when compiling a Linux build of opensurge. If you're able to run the Allegro demos, then you should be able to run opensurge as well. Adjust the shaders manually. Take a look at src/misc/org.opensurge2d.OpenSurge.yaml for a Linux recipe.

**Comment by alemart** [comment]
Feel free to reach out again if you need further help.

**Comment by IntinteDAO** [comment]
@alemart Forgive me, there is a flood in Poland and I do not have time to deal with this topic. I will write when it is good, I think within 2 weeks.

**Comment by alemart** [comment]
@IntinteDAO Take care and stay well. There were massive floods in Brazil earlier this year as well.
