### ISSUE TITLE
Font size too big to print nomally for korean

### ISSUE THREAD

**Issue by krumaska** [alemart/opensurge#15]
I think opensurge should divide the font cases and not make them recognized by the program at once.  

![screenshot, 2019-12-20 17-36-14](https://user-images.githubusercontent.com/51515055/71241782-ca33c380-234f-11ea-93aa-23370e7f67f9.png)  

`fonts/dialogbox.fnt` should be changed with two cases about for Ubuntu ttf file and Gothic ttf file.  
From what I've tested, 10 font size for Gothic would be the best.

As far as I'm concerned ...
```
font "dialogbox"
{
    truetype
    {
        source_file             "fonts/Ubuntu-M.ttf"
        size                    14
        shadow
        antialias
    }
}
```  
to  
```
font "dialogbox"
{
    truetype
    {
        source_file             "fonts/Ubuntu-M.ttf"
        size                    14
        shadow
        antialias
    }
}
font "dialogbox_ko"
{
    truetype
    {
        source_file             "fonts/GothicA1.ttf"
        size                    10
        shadow
        antialias
    }
}
```

**Comment by alemart** [comment]
I understand. Dividing the font cases is indeed the best approach. I have submitted a change in line with your request. Let me know if you can translate it now.

**Comment by alemart** [comment]
Translation accepted and issue fixed.
