### ISSUE TITLE
Future builds being provided precompiled?

### ISSUE THREAD

**Issue by Tall-Lobster** [alemart/opensurge#17]
I am trying to go along the wiki provided on the site that teaches you how to copy in SurgeScript, but it seems that it keeps references SurgeScript Versions above 0.5.0 but when I download OpenSurge, i see I have OpenSurge version 0.5.0. Does that mean i am confusing OpenSurge with SurgeScript then could someone please clarify it to me. if not please help me receive the latest version of SurgeScript

thanks

**Comment by alemart** [comment]
Hello,

SurgeScript is the scripting language that is used in Open Surge. Open Surge is a game engine. The scripting language is independent of the game engine.

You may get the latest version of Open Surge at https://opensurge2d.org (currently, it's version 0.5.1). It's precompiled and it's shipped with version 0.5.4.1 of the SurgeScript runtime.

**Comment by Tall-Lobster** [comment]
Oh sorry about that thanks for the clarification
