### ISSUE TITLE
Arabic Text not appearing correctly and can't read arabic file names

### ISSUE THREAD

**Issue by Tall-Lobster** [alemart/opensurge#18]
I was trying to create the arabic translation of the OpenSurge game but I seem to have failed as in side OpenSurge the arabic text appears as squares and that only occurs when i actually name the arabic file with only ascii based text. Will this engine get UTF support?

**Comment by alemart** [comment]
Open Surge has UTF-8 support. In addition, we use english filenames for the game assets, including the translations. I think the default font we use does not support the Arabic glyphs. We can add a new font, like we did for the Korean translation. [Google Fonts](https://fonts.google.com/) has plenty of freely licensed fonts.

If you're interested in maintaining an Arabic translation, I can gladly guide you throughout the process. Have you seen the Translation Guide at the project wiki?

Before you begin, please make sure you're using the latest version of Open Surge (currently, 0.5.1).

**Comment by Tall-Lobster** [comment]
Dear alemart,


I have seen the guide and I was actually trying to make the arabic translation, also you just reminded me OpenSurge may not have the proper fonts or some graphics rendering because Arabic text does not show up when I made the filename nonArabic.

**Comment by alemart** [comment]
The engine loads Arabic filenames just fine on Linux, but on Windows it seems that fopen() deals with ANSI by default. We would need a Microsoft extension to add this support.

In any case, writing an Arabic translation is already possible. Do you know how to add fonts to the game? It's explained in the wiki. Would the translation work if you used a font like [Cairo](https://fonts.google.com/specimen/Cairo)?

**Comment by alemart** [comment]
I have submitted code to both opensurge and surgescript that allows filenames to be in any language on Windows.

If you're still interested in working on the Arabic translation, please let me know.

**Comment by Tall-Lobster** [comment]
Dear alemart,


I am so sorry things came in the way which is why I could not reply back.

Thanks for pushing that, I really appreciate it will test it out soon.

Regarding the translation, I might be able to work on it right away but slowly i should be able to get the translation done.

Regards,

Tall Lobster

**Comment by alemart** [comment]
Cool. If you have any questions about the translation, please open an issue.
