### ISSUE TITLE
Package as Flatpak

### ISSUE THREAD

**Issue by PopeRigby** [alemart/opensurge#20]
This would make distribution easier.

**Comment by alemart** [comment]
It's been on my mind, thanks! I'll be working on it as soon as I can.

**Comment by alemart** [comment]
Open Surge is now available on Flathub 🎉

https://flathub.org/apps/details/org.opensurge2d.OpenSurge

Let me know if it works for you.

**Comment by PopeRigby** [comment]
Great! Closing.
