### ISSUE TITLE
Assetfs symlinks

### ISSUE THREAD

**Issue by jetomit** [alemart/opensurge#22]
Hi,

I’m trying to package opensurge for [Guix](https://guix.gnu.org). It would be nice to use the distribution-provided fonts where possible, so I tried replacing the bundled copies with links to system fonts. It turns out that assetfs ignores symlinks (since 80f201d), so this doesn’t work.

Is there a particular reason for disallowing symlinks? Removing bundled fonts avoids having duplicated files on the system, and allowing symlinks would make that much easier.

Thanks!

**Comment by alemart** [comment]
The reason for blocking symlinks was to disallow scripts from accessing the filesystem beyond the scope of the game. It turns out that at the time of that commit, I wasn't aware of your use case.

I have submitted code that fixes this particular issue, so let me know if it works for you.

**Comment by jetomit** [comment]
This fixed the issue. I’ll wait for the next release to submit the package, and let you know when it gets accepted. Thanks!
