### ISSUE TITLE
Please fix the reaction time design mechanic flaw of sonic

### ISSUE THREAD

**Issue by mlloewen** [alemart/opensurge#24]
Please fix the reaction time design mechanic flaw of sonic.

Put Sonic of centre of the screen, so the player has greater reaction time to obstacles that appear.

**Comment by alemart** [comment]
Hello friend,

There is no 'design flaw' (highly subjective statement) and Sonic is not a playable character in this game.

Open Surge has a widescreen aspect ratio. This will give you a greater reaction time to obstacles in comparison with classic Sonic games.

If you would like to keep the player at the centre of the screen at all times, you may modify script *scripts/core/camera.ss* to your liking. A command such as `centerCamera(player.transform.position)` will suffice. We will not be doing such a change to the camera in the main game, but you may do so in your own setup.
