### ISSUE TITLE
Audio controls

### ISSUE THREAD

**Issue by mlloewen** [alemart/opensurge#27]
It sure would be nice to have the option of controlling volume and even a mute to potently free up some resources for slow computers etc.  In the options menu most likely spot.  Thanks good work by the way you sure put a lot of work into the scripting engine.

**Comment by alemart** [comment]
This has been asked before, so I'll consider implementing this feature in a future version.

It took me a ton of work to create the scripting engine, but now it's working amazingly 😄

**Comment by Halatnikov** [comment]
one thing i would like to request is a hotkey to mute/unmute the sound completely, it may be just me but it gets a little annoying hearing the same music over and over when the level editor is open for a long time, i know you can just turn down the volume in your OS but it's a tiny bit inconvenient
