### ISSUE TITLE
Surgexception error

### ISSUE THREAD

**Issue by edotokyo** [alemart/opensurge#29]
Flatpack install  on Ubuntu 18.04
On Open Surge launch get the error message:
Failed to create a 1278x720 display

**Comment by alemart** [comment]
Hello. Do you use Wayland?

What happens if you run:
`flatpak run org.opensurge2d.OpenSurge --windowed --resolution 2`
What's the output of:
`flatpak info --show-permissions org.opensurge2d.OpenSurge`

Since you're using Ubuntu, please let me know if you can run the Open Surge snap:
```
sudo snap install opensurge
snap run opensurge
```

**Comment by edotokyo** [comment]
Hi, thanks for the quick reply. I use Xorg for compatibility reasons.
The output of:
flatpak info --show-permissions org.opensurge2d.OpenSurge
is:
he output of:
flatpak info --show-permissions org.opensurge2d.OpenSurge
Nice, both flatpack and snap installs run now.
Small issues:
-when run on flatpack:
Gtk-Message: 09:55:42.281: Failed to load module "overlay-scrollbar"
Gtk-Message: 09:55:42.282: Failed to load module "atk-bridge"
Gtk-Message: 09:55:42.294: Failed to load module "canberra-gtk-module"
-when run on snap:
(process:29024): Gtk-WARNING **: 09:43:18.291: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 09:43:18.337: Failed to load module "overlay-scrollbar"
Gtk-Message: 09:43:18.337: Failed to load module "gail"
Gtk-Message: 09:43:18.337: Failed to load module "atk-bridge"
Gtk-Message: 09:43:18.360: Failed to load module "canberra-gtk-module"
-On flatpack version, can't locate opensurge folder containing levels and sprites files.
-On snap version, opensurge folder containing levels and sprites files installed in read-only root location:
 /snap/opensurge/10/usr/share/games/opensurge/
which makes modifications and editing impossible.
N.B.: I checked the How to make a level tutorial. Nice wiki by the way:)

**Comment by alemart** [comment]
Thank you for the feedback.

Can you run the snap version with resolution x3?
`snap run opensurge --windowed --resolution 3`
How about the flatpak version?
`flatpak run org.opensurge2d.OpenSurge --windowed --resolution 3`

Can you run the game in fullscreen mode? (menu -> options -> fullscreen)

Regarding the opensurge folders for snap & flatpak: I have updated the How to make a level tutorial and linked the directories there for clarity. You can modify sprites, levels and more by placing your files on the read-write directories (e.g., when you save a level, it's saved on those). The read-write directories are specified on the [project README](https://github.com/alemart/opensurge/blob/master/README.md).

Let me know if you have any difficulty.

**Comment by edotokyo** [comment]
Here are the results running snap and flatpack versions:

snap run opensurge --windowed --resolution 3
(process:25876): Gtk-WARNING **: 10:32:49.606: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 10:32:49.675: Failed to load module "overlay-scrollbar"
Gtk-Message: 10:32:49.675: Failed to load module "gail"
Gtk-Message: 10:32:49.675: Failed to load module "atk-bridge"
Gtk-Message: 10:32:49.698: Failed to load module "canberra-gtk-module"

flatpak run org.opensurge2d.OpenSurge --windowed --resolution 3
Gtk-Message: 10:33:36.231: Failed to load module "overlay-scrollbar"
Gtk-Message: 10:33:36.255: Failed to load module "atk-bridge"
Gtk-Message: 10:33:36.362: Failed to load module "canberra-gtk-module"

Fullscreen mode is running fine for both.
Game also running.
Transfered from read-only all /var/lib/flatpak/app/org.opensurge2d.OpenSurge/x86_64/stable/376de1e10ed256c43d4a5b57694ea21402b06289ba0a4fc2ad191f6adf7d6b0f/files/share/opensurge directories and files to read-write /home/shoyusha/.var/app/org.opensurge2d.OpenSurge/data/opensurge2d/opensurge and could successfully save modified level with modified sprite.
So far so good.

**Comment by alemart** [comment]
Glad to know it's working for you. If you simply run `flatpak run org.opensurge2d.OpenSurge`, the game should run just fine.

You don't need to transfer all read-only files to the read-write locations, as the game will read from (and write to) these places automatically. The read-write locations take precedence over the read-only ones. If you update the game and we change an asset (a sprite, a level, etc), you may not see the updated version. It's recommended that you use the read-write locations only for the files you need, never for all of them. So I suggest that you clean up the read-write folders, leaving only the files you need (the level editor will save the data to the read-write folders automatically). Did you have a problem with this?

It all seems to be working fine for you, but if you have any further questions, feel free to open an issue.
