### ISSUE TITLE
Corrupted obstacle map resulting in segmentation fault

### ISSUE THREAD

**Issue by codylico** [alemart/opensurge#3]
### Situation

I have a level involving enemies with the `SurgeEngine.Behaviors.Platformer` behavior.

### Expected behavior

When the player loses a life in the level, the game properly resets to the last checkpoint.

### Observed behavior

When the player loses a life in the level, sometimes the game crashes with a segmentation fault instead of restarting the level. The issue seems to involve an access to a bad `collisionmask_t` pointer from a corrupted (freed?) `obstacle_map_t` instance used by the sensors in the `SurgeEngine.Behaviors.Platformer`.

### System details

Commit: e67435453c7d8223a9dca12af7700979e0fc5761
SurgeScript commit: alemart/surgescript@6d3ab4489b8e04b0f0cc8dc1ef4cc969c6ac5624
CMake configuration: (using ccmake)
```
BLEEDING_EDGE_VERSION:STRING=custom
BLEEDING_EDGE:BOOL=ON
CMAKE_BUILD_TYPE:STRING=Release
LALLEGRO:FILEPATH=/usr/lib/x86_64-linux-gnu/liballegro.so
LSURGESCRIPT:FILEPATH=(build of SurgeScript at commit 6d3ab44).a
USE_A5:BOOL=ON
USE_OPENAL:BOOL=OFF
USE_STATIC:BOOL=ON
...
```
OS: Ubuntu 18.04.2 LTS
OS-type: 64-bit

## Minimal level that breaks

```
// ------------------------------------------------------------
// Open Surge Engine 0.5.0-sandbox-dev level
// ------------------------------------------------------------

// header
name "ObstacleTest"
author "YOUR_NAME_HERE"
license "CC-0"
version "1.0"
requires "0.5.0"
act 1
theme "themes/template.brk"
bgtheme "themes/template.bg"
spawn_point 128 9968
setup "Default Setup" "Example Setup"
players "Tux"

// bricks
brick 0 896 10000
brick 0 960 10000
brick 0 0 10000
brick 0 64 10000
brick 0 128 10000
brick 0 192 10000
brick 0 256 10000
brick 0 320 10000
brick 0 384 10000
brick 0 448 10000
brick 0 512 10000
brick 0 576 10000
brick 0 640 10000
brick 0 704 10000
brick 0 768 10000
brick 0 832 10000
brick 0 384 1000

// entities
entity "GreenMarmot" 16 10000 "389647dd856c1642"
entity "Powerup Trap" 1008 10000 "a8b0e3c8da771eee"

// EOF
```

### Comments

After noticing the issue, I saw commit alemart/surgescript@129a74be02f124e5be031e4f27d0c17899babf74 and wondered if this new commit may be related. I have not yet tried it, and wanted to post the issue in case it is unrelated.

**Comment by alemart** [comment]
Thank you for reporting. I have submitted code to fix the issue. Let me know if it persists.

**Comment by codylico** [comment]
I just got internet again. I will check out the code fix next chance I get.

Thanks,

**Comment by codylico** [comment]
Looks like the fix works.

Thanks.
