### ISSUE TITLE
Open Surge has weird crocodile app icon

### ISSUE THREAD

**Issue by Wuzzy2** [alemart/opensurge#6]
The application icon of Open Surge 0.5 is a weird crocodille.

**Comment by alemart** [comment]
Aha, that's Alex from the Allegro library :-) In the Linux build, he shines. I'll see what I can do, so Surge appears. Surge appears on the Windows build.

**Comment by Wuzzy2** [comment]
Yes, I'm using Linux. You got me. :)

**Comment by alemart** [comment]
Take a look at the latest commit and see if a new icon appears for you. That neat _allegator_ will be missed :)

**Comment by Wuzzy2** [comment]
The new icon works now.
