### ISSUE TITLE
You can collect "coins" when dying

### ISSUE THREAD

**Issue by Wuzzy2** [alemart/opensurge#60]
If you die because you ran into spikes, an enemy, etc. you will still be able to collect "coins" as you fall out of the level, and the energy will be added. The coins just need to be in your path while you fall out.

This is not game-breaking, just a little odd.

Tested in: 3684b17f2cf028f174910314d43cdfdd60f6d0be

**Comment by alemart** [comment]
Thank you for bringing this up.

I'll be taking a look at this issue.
