### ISSUE TITLE
Port to OSX Intel and maybe PPC

### ISSUE THREAD

**Issue by Hawk2811** [alemart/opensurge#62]
I'm wanting to help the project by making a port to Mac OS X Platforms at the moment I'm using a Hackintosh without Dual Boot with Windows Because of TPM2.0 : (

But do you have any documentation on port to other platforms?

**Comment by alemart** [comment]
Hi, thanks for your interest in the project.

There is a cross compiling guide in [our wiki](https://wiki.opensurge2d.org). The game engine is built using the Allegro game development library. Allegro is cross-platform, so porting the engine shouldn't be too difficult. I don't own a Mac, so I'm unable to tell you the specifics.

**Comment by Hawk2811** [comment]
I tried compiling OpenSurge on my Hackintosh with macOS Catalina but cmake couldn't find the allegro5 library

printscreen of terminal output
![Captura de Tela 2021-12-20 às 15 28 23](https://user-images.githubusercontent.com/55853571/146815606-853561d0-272f-4458-ba0c-559e0aa893dd.png)

**Comment by alemart** [comment]
What this means is that Allegro 5 is not correctly installed. You can install the latest Allegro via Homebrew:

```
brew install allegro
brew install pkg-config
```

More info at:
* https://formulae.brew.sh/formula/allegro
* https://github.com/liballeg/allegro_wiki/wiki/Quickstart

**Comment by alemart** [comment]
@Hawk2811 Any progress so far?

**Comment by Hawk2811** [comment]
> @Hawk2811 Any progress so far?

I'm on vacation at the moment when I get back I'll tell you

**Comment by alemart** [comment]
Okay. If I can be of help to you, feel free to contact me again.

**Comment by alemart** [comment]
**Update**

A community member was able to successfully compile Open Surge on macOS. It works! Downloads are available at https://forum.opensurge2d.org/viewtopic.php?id=2133

**Comment by alemart** [comment]
To whom it might interest: the latest release of the game (0.6.0 at the time of this writing) is also available for macOS. An application bundle is being provided by community member SGWaS.

https://forum.opensurge2d.org/viewtopic.php?id=2135
