### ISSUE TITLE
Update Bosnian, Dutch, Serbian translations

### ISSUE THREAD

**Issue by alemart** [alemart/opensurge#71]
Hi @SecularSteve . Did you receive my e-mail? We're releasing a new version of the game in the next few days. How is the translation work going?

**Comment by SecularSteve** [comment]
Give me a couple of days (at least until Wednesday), and I'll have them all by then (no delays this time).

Sorry for disappearing for so long. Personal circumstances keep getting in the way of my hobbies. I hope we can get back on better terms.

**Comment by SecularSteve** [comment]
done... check if I missed anything.

**Comment by alemart** [comment]
Did you test your translations?

**Comment by alemart** [comment]
@SecularSteve
