### ISSUE TITLE
Conversion to use a different rendering library?

### ISSUE THREAD

**Issue by JadeVand** [alemart/opensurge#82]
Would it be possible to allow this engine to run with a separate rendering library like SDL2 or Raylib. Allegro is nice but I have to jump through hoops to get the engine to compile because Allegro has a whole set of different dependencies in order to first compile that library then to compile the engine.

**Comment by alemart** [comment]
Allegro has a SDL backend. Depending on your operating system, you may just get pre-compiled binaries. What's your operating system?

**Comment by JadeVand** [comment]
I'm currently on MacOS, I did manage to get it to compile but as I mentioned it was quite a bit of work. I did want to make changes to the engine which is why I preferred the source over the precompiled binaries.

**Comment by alemart** [comment]
Glad to know that you managed to compile Allegro. Once you do it, compiling the engine is simple.
