### ISSUE TITLE
[Bug?] Holding Fire 1 auto-jumps

### ISSUE THREAD

**Issue by Soufon7** [alemart/opensurge#83]
I'm not sure if this was a deliberate change, but I didn't see anything directly pertaining to it going through the commits. If so, having it be toggleable would be nice, since it can mess with jumping into curved ceilings - you can't hold jump to carry speed into running on the ceiling in those cases.
Wasn't present from at least v0.6.1.0-230119-dev.

**Comment by alemart** [comment]
Yes, I'm aware of the issue and it will be fixed soon.
