### ISSUE TITLE
[DOC] SurgeScript version 0.6.0 or later

### ISSUE THREAD

**Issue by pirate486743186** [alemart/opensurge#84]
The readme sais 0.6.0 but the latest is 0.5.6.1

**Comment by alemart** [comment]
I'm developing in the master branch. These requirements refer to the version in development. The latest release has different requirements.

**Comment by alemart** [comment]
If you get the dependencies currently specified in the README, you'll also be able to compile the latest release. Is the issue clarified?

**Comment by alemart** [comment]
Thank you for your feedback.
