### ISSUE TITLE
[DOC/BUG?] Entity limit problems

### ISSUE THREAD

**Issue by Soufon7** [alemart/opensurge#85]
As I was making a large stage, entities towards the beginning of the level started to disappear. I assume this is because there is a limit for entities placed, as is with most other Maker-style games, but there's no documentation on the Wiki on what that limit is. Alternatively, having it displayed in the editor itself somewhere would be very helpful for managing larger stages, though that would require it keeping track of how many are placed.
If there being a limit is unintended behavior, than just treat this as a bug report.

**Comment by alemart** [comment]
Hi! Which version are you using?

Entities are not meant to disappear, unless they are tagged `"disposable"`. Would you share your .lev file, as well as other necessary files to reproduce the issue?

**Comment by Soufon7** [comment]
I'm using the latest development version from the forums, 0.6.1-windows-20230724-dev
Here's the level:
https://drive.google.com/file/d/1x8NqG7GAFmSfQ2M_XtiocjV5WmCqaVbS/view?usp=sharing

**Comment by alemart** [comment]
Would you elaborate further on how to reproduce the issue? I recognize that some common entities (such as layers, tubes and collectibles) seem to be missing when I open the level, but I was unable to make any of them disappear.

What can you do, specifically and step by step, to get the entities to disappear? In addition, does the issue happen in the previous dev build?

**Comment by Soufon7** [comment]
Sorry for getting back to you late, but all that I did was place more and that caused entities to vanish. It might have something to do with increasing the level boundary? That, or it's stemming from the set resolution - I increased it to 640x360 for the project this level's for.

**Comment by alemart** [comment]
Can you compile the source code?

> It might have something to do with increasing the level boundary? That, or it's stemming from the set resolution - I increased it to 640x360 for the project this level's for.

No, I don't think it's related to the level boundary nor to the set resolution.

**Comment by alemart** [comment]
Would you confirm whether or not the issue happens in the previous dev build, 20230423-dev?

**Comment by Soufon7** [comment]
It doesn't occur on that older build, no - placing a horde of entities/bricks worked fine.

**Comment by alemart** [comment]
Does my latest commit aae6b72b1565c20bb7a3838ba78426aff175a1fb fix the issue? If you're not able to compile the game, you may try again in the next dev build. Let me know if it works for you.

> It doesn't occur on that older build, no - placing a horde of entities/bricks worked fine.

The entity system has recently been rewritten for increased performance. The sudden disappearance of entities is a bug.

**Comment by alemart** [comment]
Is it working in the latest dev build, 20230903-dev?

**Comment by Soufon7** [comment]
The bug does not occur anymore, thanks!
