### ISSUE TITLE
Characters who can't naturally roll can keep roll state while Down is held

### ISSUE THREAD

**Issue by Soufon7** [alemart/opensurge#87]
If a character's .chr file has the roll ability blocked, but the character is put into roll state by scripts, etc, they can roll from landing from midair like characters that _do_ have the roll ability.

**Comment by Soufon7** [comment]
I'm not really for blocking them from rolling at _all_, just them being able to roll "again" after being forced to roll seems off to me.
Blocking it 100% would make zoom tubes and the like incompatible with those characters.

**Comment by alemart** [comment]
Currently, only the manual activation of the rolling is blocked. We can keep this method too.

Please confirm: do you refer to the situation that is in this video?

https://github.com/alemart/opensurge/assets/221477/ffe8e1fa-5920-4877-bf95-db6f912370eb

**Comment by Soufon7** [comment]
Yeah.

**Comment by alemart** [comment]
Okay, thank you.
