### ISSUE TITLE
[feature] Stair bricktype

### ISSUE THREAD

**Issue by Soufon7** [alemart/opensurge#89]
![example](https://github.com/alemart/opensurge/assets/109707433/791a2079-1201-4996-b5ca-b51c86a2f092)

Would be useful in making non-Sonic like games or just for, well, stairs. Setting a player's slope factor to 0 comes close to this, but slopes still affect jumping in that case.

**Comment by alemart** [comment]
You can use the engine to make various kinds of platformers, as well as non-platformers.

Your request can be fulfilled with a companion script. It can go along these lines:

```cs
// object-level variables
player = parent;
previouslyJumping = false;

...

fun lateUpdate()
{
    player.angle = 0;

    if(player.jumping && !previouslyJumping) {
        player.xsp = 0;
        player.ysp = -390;
    }

    previouslyJumping = player.jumping;
}
```
