### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by alemart** [alemart/opensurge#90]
Hi @dart-bird !

Would you still be interested in maintaining the Korean translation of the game?

**Comment by dart-bird** [comment]
> Hi @dart-bird !
> 
> Would you still be interested in maintaining the Korean translation of the game?

It's great to have you here, and contributing to open-source projects is always appreciated. However, I'm quite busy with my academic schedule at the moment, so the translation process might take a bit longer than expected. Is that alright?

**Comment by dart-bird** [comment]
> Hi @dart-bird !
> 
> Would you still be interested in maintaining the Korean translation of the game?

Sure.
Contributing to open source projects is always a pleasure for me! However, I'm very busy with my academic schedule right now, so the translation process might take a little longer than expected, is that okay?

**Comment by alemart** [comment]
Thanks for your reply!

We're approaching a new release, and soon we'll enter the string freeze period. How long do you think it will take for you to write the translation?

**Comment by dart-bird** [comment]
> Thanks for your reply!
> 
> We're approaching a new release, and soon we'll enter the string freeze period. How long do you think it will take for you to write the translation?

I think it will be about six months 🥲, but it could be less.

**Comment by alemart** [comment]
Okay, so it would take you about 6 months to update the translation strings in [this text file](https://github.com/alemart/opensurge/blob/master/languages/english.lng)? In this case, it won't be possible to ship your translation with the upcoming release. We're about to enter the string freeze period.
