### ISSUE TITLE
Update Esperanto translation

### ISSUE THREAD

**Issue by alemart** [alemart/opensurge#92]
Hi @jorgesumle !

Have you received my e-mail about the Esperanto translation?

**Comment by jorgesumle** [comment]
> Have you received my e-mail about the Esperanto translation?

Yes, I translated some strings, but now I don't have a lot of free time.

> Please submit your translation no later than March 31st, 2024

I'll send you a pull request before that date.

**Comment by alemart** [comment]
Thanks for the confirmation! I await your translation.
